### ISSUE TITLE
场次、票价选择

### ISSUE THREAD

**Issue by gaoyh18** [MakiNaruto/Automatic_ticket_purchase#1]
可以跑通而且蛮快的！非常感谢~
想问一下有没有选择演出时间和票价的模块可以补充呀
我也在参考原代码自己添加这部分，但之前没接触过网页相关所以不知道能不能行，加油
再次感谢！！

**Comment by gaoyh18** [comment]
#场次
self.driver.find_elements_by_xpath('//html//body//div[@class = "perform__order__select perform__order__select__performs"]//div[2]//div//div[2]//span[1]')[0].click() 
#如果左上角标了“预售”，就有两个span，选第二个是span[1]，所以到底从0开始还是从1开始
#价格
self.driver.find_elements_by_xpath('//html//body//div[@class = "perform__order__select"]//div[text()=\"%s\"]'%i)[0].click()
#写进循环里了，依次尝试每个i（价格），选完后要break
#数量
self.driver.find_elements_by_xpath('//html//body//div[@class = "perform__order__price"]//div[2]//div//div//input')[0].send_keys('4')
#原代码一个个加，效果是一样的，哪个更快暂时没结论

**Comment by MakiNaruto** [comment]
> 可以跑通而且蛮快的！非常感谢~
> 想问一下有没有选择演出时间和票价的模块可以补充呀
> 我也在参考原代码自己添加这部分，但之前没接触过网页相关所以不知道能不能行，加油
> 再次感谢！！

self.driver.find_elements_by_xpath('//div[@class = "perform__order__select perform__order__select__performs"]//div[2]//div//div[x]')[0].click()  #默认购票日期的选择,x为日期的选择，1，2，3....  
这里推荐你用下谷歌的插件，叫XPath Helper，可以帮助你理解元素的定位
我也是刚接触这个，我们一起进步哈^ . ^

**Comment by 646420882** [comment]
> #场次
> self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select perform__order__select__performs"]//div[2]//div//div[2]//span[1]')[0].click()
> #如果左上角标了“预售”，就有两个span，选第二个是span[1]，所以序号到底从0开始还是从1开始？？
> #价格
> self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select"]//div[text()="%s"]'%i)[0].click()
> #写进循环里了，依次尝试每个i（价格），选完后要break
> #数量
> self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__price"]//div[2]//div//div//input')[0].send_keys('4')
> #原代码一个个加，效果是一样的，哪个更快暂时没结论

最后一个，[last()]

**Comment by pengzirui** [comment]
> #场次
> self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select perform__order__select__performs"]//div[2]//div//div[2]//span[1]')[0].click()
> #如果左上角标了“预售”，就有两个span，选第二个是span[1]，所以序号到底从0开始还是从1开始？？
> #价格
> self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select"]//div[text()="%s"]'%i)[0].click()
> #写进循环里了，依次尝试每个i（价格），选完后要break
> #数量
> self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__price"]//div[2]//div//div//input')[0].send_keys('4')
> #原代码一个个加，效果是一样的，哪个更快暂时没结论

请问#场次 中，xpath的span[1]是预售，span[2]是场次信息，为什么click span[1]？以及，self.driver.find_elements_by_xpath('')[0].click()中的[0]是什么意思？

**Comment by gaoyh18** [comment]
> > #场次
> > self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select perform__order__select__performs"]//div[2]//div//div[2]//span[1]')[0].click()
> > #如果左上角标了“预售”，就有两个span，选第二个是span[1]，所以序号到底从0开始还是从1开始？？
> > #价格
> > self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select"]//div[text()="%s"]'%i)[0].click()
> > #写进循环里了，依次尝试每个i（价格），选完后要break
> > #数量
> > self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__price"]//div[2]//div//div//input')[0].send_keys('4')
> > #原代码一个个加，效果是一样的，哪个更快暂时没结论
> 
> 最后一个，[last()]

哦哦这个我后来试过发现不对，如果我那样写是直接在默认的1后面再加一个数字，就是14，如果超出限购数量就默认为限购数量，其实是不对的。你的意思是在send前面加last()可以删除1吗？还是其他什么意思？

**Comment by gaoyh18** [comment]
> > #场次
> > self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select perform__order__select__performs"]//div[2]//div//div[2]//span[1]')[0].click()
> > #如果左上角标了“预售”，就有两个span，选第二个是span[1]，所以序号到底从0开始还是从1开始？？
> > #价格
> > self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__select"]//div[text()="%s"]'%i)[0].click()
> > #写进循环里了，依次尝试每个i（价格），选完后要break
> > #数量
> > self.driver.find_elements_by_xpath('//html//body//div[@Class = "perform__order__price"]//div[2]//div//div//input')[0].send_keys('4')
> > #原代码一个个加，效果是一样的，哪个更快暂时没结论
> 
> 请问#场次 中，xpath的span[1]是预售，span[2]是场次信息，为什么click span[1]？以及，self.driver.find_elements_by_xpath('')[0].click()中的[0]是什么意思？

就是说如果价格这个标签上左上角有“预售”字样的话，span的指向会有一点变化，但是这个无所谓啦，后来发现把span那个删掉也没关系，click的都是那一个div。这个你可以在网页中按F12去看一下，其实很容易看懂。[0]这个我也不太清楚，给的代码里面都加了的，我也没有去查或者去测试他的功能。

**Comment by caiyudian** [comment]
elif buybutton == "立即预定": 

纠结了半个小时发现是立即预订。。。
