### ISSUE TITLE
请问如何修改票面选择？

### ISSUE THREAD

**Issue by zezhishao** [MakiNaruto/Automatic_ticket_purchase#11]

**Comment by zezhishao** [comment]
已经Get了，明天Jay的门票就靠你了！

**Comment by pengzirui** [comment]
请问下，票面选择是如何解决的？

**Comment by zezhishao** [comment]
> 请问下，票面选择是如何解决的？

使用XPath插件(chrome商店里有）获取到票面按钮的value，然后在程序中模拟点击即可。
可以参考程序中增加购票数量的操作。
但是这个抢票程序用处不大，只是帮助运行到了点击“立刻预定”按钮，后面“同意并立刻提交订单”没有操作，也就无法锁定票。自己去点击提交订单的话，太慢了，昨天Jay的票没抢到。

另外吐槽一下，大麦网有的时候不是总代，这个要看清了，否则票量太少根本抢不到的！

**Comment by pengzirui** [comment]
我获取到的某一票价的xpath是/html/body/div[2]/div/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[2]/div/div[3]，但是在click的时候需要做self.driver.find_elements_by_xpath('/html/body/div[2]/div/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[2]/div/div[3]')**[0]**.click(),否则就会报错。请问您知道这里的[0]是什么作用么？

**Comment by zezhishao** [comment]
> 我获取到的某一票价的xpath是/html/body/div[2]/div/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[2]/div/div[3]，但是在click的时候需要做self.driver.find_elements_by_xpath('/html/body/div[2]/div/div[1]/div[1]/div/div[2]/div[3]/div[6]/div[2]/div/div[3]')**[0]**.click(),否则就会报错。请问您知道这里的[0]是什么作用么？

我对网页的东西也只是略知一二，不懂原理。从运行过程上看，
```python
self.driver.find_elements_by_xpath
```
的返回结果是一个List，List的第一个元素就是需要获得的按钮。（这个List只有一个元素）

**Comment by pengzirui** [comment]
原来如此！谢谢！！！！！！！！！！

**Comment by pengzirui** [comment]
> > 请问下，票面选择是如何解决的？
> 
> 使用XPath插件(chrome商店里有）获取到票面按钮的value，然后在程序中模拟点击即可。
> 可以参考程序中增加购票数量的操作。
> 但是这个抢票程序用处不大，只是帮助运行到了点击“立刻预定”按钮，后面“同意并立刻提交订单”没有操作，也就无法锁定票。自己去点击提交订单的话，太慢了，昨天Jay的票没抢到。
> 
> 另外吐槽一下，大麦网有的时候不是总代，这个要看清了，否则票量太少根本抢不到的！

啊对了！是可以按照同样的方法模拟点击同意并立刻提交订单按钮的，最远可以走到zfb扫码付款这一步，这个时候已经锁订单了，扫码可以慢一点无所谓。希望你下次能够抢票成功QaQ

**Comment by zezhishao** [comment]
> > > 请问下，票面选择是如何解决的？
> > 
> > 
> > 使用XPath插件(chrome商店里有）获取到票面按钮的value，然后在程序中模拟点击即可。
> > 可以参考程序中增加购票数量的操作。
> > 但是这个抢票程序用处不大，只是帮助运行到了点击“立刻预定”按钮，后面“同意并立刻提交订单”没有操作，也就无法锁定票。自己去点击提交订单的话，太慢了，昨天Jay的票没抢到。
> > 另外吐槽一下，大麦网有的时候不是总代，这个要看清了，否则票量太少根本抢不到的！
> 
> 啊对了！是可以按照同样的方法模拟点击同意并立刻提交订单按钮的，最远可以走到zfb扫码付款这一步，这个时候已经锁订单了，扫码可以慢一点无所谓。希望你下次能够抢票成功QaQ

嗯！昨天抢完我才发现这个问题，已经改了代码了，等待下一次抢票。。。
