### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by alang1999** [MakiNaruto/Automatic_ticket_purchase#16]
您好，请问出现这样的错误是什么原因？
TypeError: __init__() got an unexpected keyword argument 'options'

**Comment by MakiNaruto** [comment]
以后可以的话请尽量发送完整的报错信息，看起来似乎是由于初始化selenium导致的，请确认selenium版本是否与 requirements.txt 文件内保持一致，因为该版本在我这里没有该问题。

**Comment by MakiNaruto** [comment]
> 您好，请问出现这样的错误是什么原因？ TypeError: **init**() got an unexpected keyword argument 'options'

以后可以的话请尽量发送完整的报错信息，看起来似乎是由于初始化selenium导致的，请确认selenium版本是否与 requirements.txt 文件内保持一致，因为该版本在我这里没有该问题。

**Comment by alang1999** [comment]
Traceback (most recent call last):
  File "D:\Python3.7\Automatic_ticket_purchase.py", line 339, in <module>
    a.run()
  File "D:\Python3.7\Automatic_ticket_purchase.py", line 299, in run
    login_status = self.account_login('account')
  File "D:\Python3.7\Automatic_ticket_purchase.py", line 105, in account_login
    driver = webdriver.Chrome(chromedriver, options=option)
  File "D:\Python3.7\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "D:\Python3.7\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "D:\Python3.7\lib\site-packages\selenium\webdriver\common\service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service D:\Python3.7\chromedriver_windows unexpectedly exited. Status code was: 1

**Comment by MakiNaruto** [comment]
> Traceback (most recent call last): File "D:\Python3.7\Automatic_ticket_purchase.py", line 339, in a.run() File "D:\Python3.7\Automatic_ticket_purchase.py", line 299, in run login_status = self.account_login('account') File "D:\Python3.7\Automatic_ticket_purchase.py", line 105, in account_login driver = webdriver.Chrome(chromedriver, options=option) File "D:\Python3.7\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in **init** self.service.start() File "D:\Python3.7\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start self.assert_process_still_running() File "D:\Python3.7\lib\site-packages\selenium\webdriver\common\service.py", line 111, in assert_process_still_running % (self.path, return_code) selenium.common.exceptions.WebDriverException: Message: Service D:\Python3.7\chromedriver_windows unexpectedly exited. Status code was: 1

请检查你selenium的版本

**Comment by alang1999** [comment]
跟你的版本一样

**Comment by MakiNaruto** [comment]
> 跟你的版本一样

检查你自己的环境，我起新环境进行安装并没有出现你的问题。
