### ISSUE TITLE
[fix] 适配不需要选择观演人的场次

### ISSUE THREAD

**Issue by ronething** [MakiNaruto/Automatic_ticket_purchase#18]
https://github.com/MakiNaruto/Automatic_ticket_purchase/blob/69f5613680afba8a09576041a7a129bffa3c95cf/Automatic_ticket_purchase.py#L262-L263

如果是不需要选择观演人的场次，会有异常发生

类似 `'Nonetype' object has no attribute 'group'` 之类

这里应该需要先判断  `re.search('dmViewerPC_[0-9]*', dm_viewer_pc)` 是否为 None，有时间我修复一下提个 pr

**Comment by MakiNaruto** [comment]
> 如果是不需要选择观演人的场次，会有异常发生

这个情况没注意到，等你补丁奥~

**Comment by ronething** [comment]
好的。这两天简单修复下。看你好像更新选座的了。顺便过下逻辑。
