### ISSUE TITLE
在使用Cookie登录的时候!长时间等待之后会产生以下错误!可能是多次重定向出现问题.

### ISSUE THREAD

**Issue by xhay125** [MakiNaruto/Automatic_ticket_purchase#20]
requests.exceptions.SSLError: httpconnectionpool (host='detail.damai.cn'， port=443): Max retries exceeded with url: /subpage? damai&scenario=itemsku&dataType=&dataId=&privilegeActId=(导致的SSLError(SSLEOFError(8， 'EOF发生在违反协议(_ssl.c:1123)'))

**Comment by MakiNaruto** [comment]
不太清楚使用cookies登录为什么会长时间等待，是debug么？而且正常来说也不会在登录时做长时间等待呀。

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
