### ISSUE TITLE
提交信息

### ISSUE THREAD

**Issue by XUEYULIANG** [MakiNaruto/Automatic_ticket_purchase#21]
身份证信息在提交订单的时候显示null

**Comment by MakiNaruto** [comment]
没明白为什么会有身份证信息，仅需要名字与大麦网存储信息的进行对应即可。
如果说是对于名称及前面步骤都ok，在订单提交时出现的bug，请贴完整的ERROR INFO。

> 身份证信息在提交订单的时候显示null

**Comment by Redlove2015** [comment]
![微信图片_20220622163838](https://user-images.githubusercontent.com/54393734/174984181-de88734c-270f-4fea-a04b-c40df0ccf2e3.jpg)

应该说的是这个，我测试抢到票之后，点开订单里面有我的名字但是我的身份证号是null. 另外请问能否提供可视化窗口（Chrome） 能够看到自动运行的流程，方便精准的判断是否哪里出现设置错误。

**Comment by MakiNaruto** [comment]
1. 请问是已在大麦网上添加了自己的身份证信息了嘛？

> 另外请问能否提供可视化窗口（Chrome） 能够看到自动运行的流程，方便精准的判断是否哪里出现设置错误。

2. 去掉注释即可
Tools.py   →  account_login()
 # option.add_argument('headless')

**Comment by Redlove2015** [comment]
> 
谢谢！
1.是的，实名认证均已完成，并且完整填写了观演人信息。票能够支付，但是显示有问题，有点担心是否会出现到时候身份证号对不上的情况。

**Comment by Redlove2015** [comment]
> > 
> 
> 谢谢！ 1.是的，实名认证均已完成，并且完整填写了观演人信息。票能够支付，但是显示有问题，有点担心是否会出现到时候身份证号对不上的情况。

这是在没有完成支付的时候的显示，尚未测试支付完成后

**Comment by ShaunPan1** [comment]
一打开提示invalid syntax

**Comment by MakiNaruto** [comment]
> 但是显示有问题，有点担心是否会出现到时候身份证号对不上的情况。

请问有通过浏览器在官网查看已购票的信息么？如果页面端和app端都出现同样的问题说明此方式可能包含风险😭

**Comment by Redlove2015** [comment]
> > 但是显示有问题，有点担心是否会出现到时候身份证号对不上的情况。
> 
> 请问有通过浏览器在官网查看已购票的信息么？如果页面端和app端都出现同样的问题说明此方式可能包含风险😭

谢谢提醒，我看了一下网页端没有问题！
另外请问一下是不是只能同时登录在一个地方呢，能否copy两个项目，登录同一个账号进行同时进行抢票

**Comment by MakiNaruto** [comment]
> 另外请问一下是不是只能同时登录在一个地方呢，能否copy两个项目，登录同一个账号进行同时进行抢票

这个没问题的，加入多线程同时抢或者开多个脚本都可以。

**Comment by Redlove2015** [comment]
> > 另外请问一下是不是只能同时登录在一个地方呢，能否copy两个项目，登录同一个账号进行同时进行抢票
> 
> 这个没问题的，加入多线程同时抢或者开多个脚本都可以。


谢谢，因为中午抢告五人的时候，远程电脑登录了提前十分钟开始运行，没有任何提示，另外本地的电脑在00分的时候运行，远程提示购买参数必备异常，本地的就直接报缺货了。 我还以为是因为远程的登录掉线了。谢谢解答！

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
