### ISSUE TITLE
获取购买必备参数异常

### ISSUE THREAD

**Issue by 1097452462** [MakiNaruto/Automatic_ticket_purchase#22]
请问如果有日期、场次等信息是包含在哪个参数里面

**Comment by MakiNaruto** [comment]
日期/场次，是由具体的SKUID来定位的，可以看STEP1

> 请问如果有日期、场次等信息是包含在哪个参数里面

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
