### ISSUE TITLE
登录失败, 请检查登录账号信息。若使用保存的cookies，则删除cookies文件重新尝试

### ISSUE THREAD

**Issue by Ppinnacle** [MakiNaruto/Automatic_ticket_purchase#23]
请问我这是哪里出了问题 谷歌我清过了

**Comment by Ppinnacle** [comment]
忘记删掉原路径里的文件了 已解决

**Comment by Ophiee** [comment]
大佬，请问一下你之后是怎么解决的，原路径里的文件是指什么呀？我用账号密码也登录失败。

**Comment by Ppinnacle** [comment]
> 大佬，请问一下你之后是怎么解决的，原路径里的文件是指什么呀？我用账号密码也登录失败。

把你的cookie删干净试一下 不过这个项目停止维护了吧好像
