### ISSUE TITLE
出现购买必备参数异常

### ISSUE THREAD

**Issue by Ppinnacle** [MakiNaruto/Automatic_ticket_purchase#24]
购买参数必备异常是不是说明没抢到，再运行就直接报缺货了

**Comment by MakiNaruto** [comment]
> 购买参数必备异常是不是说明没抢到，再运行就直接报缺货了

参数错误的问题有很多，根据你的描述很有可能是，该错误就是票源没了，导致提交的参数是不可用状态，所以导致报参数错误。

**Comment by Ppinnacle** [comment]
> 

ok明白了 感谢！

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮

**Comment by dishiyicijinqiu** [comment]
> 

没用了，我都跑通了，那两个参数都获取到了，也能提交成功了。但现在问题是他不支持网页端购票了
