### ISSUE TITLE
run了之后打不开chrome

### ISSUE THREAD

**Issue by qunzai** [MakiNaruto/Automatic_ticket_purchase#25]

**Comment by lhw559** [comment]
> 
找到电脑chrome的根目录文件夹里就有，然后复制到工程文件夹

**Comment by lhw559** [comment]
> 

找到电脑chrome的根目录文件夹，然后复制到工程文件夹

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
