### ISSUE TITLE
String is updata

### ISSUE THREAD

**Issue by QuNimom** [MakiNaruto/Automatic_ticket_purchase#26]
``   elif ticket_sku_status == '立即购买':
                buy_serial_number = '{}_{}_{}'.format(self.item_id, self.buy_nums, sku_id)
                submit_order_info = self.step2_click_buy_now(ex_params, buy_serial_number)
                break``
``   elif ticket_sku_status == '立即预订':
                buy_serial_number = '{}_{}_{}'.format(self.item_id, self.buy_nums, sku_id)
                submit_order_info = self.step2_click_buy_now(ex_params, buy_serial_number)
                break``
若进入死循环 修改为立即预订 即可进行购买

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
