### ISSUE TITLE
为什么运行之后没有信息回馈，也没有显示订购成功

### ISSUE THREAD

**Issue by Zjm1900** [MakiNaruto/Automatic_ticket_purchase#28]
(ticket) E:\Code\Automatic_ticket_purchase-master\Automatic_ticket_purchase-master>python Automatic_ticket_purchase.py          

之后就没有其它东西出现了
![image](https://user-images.githubusercontent.com/39974339/178739371-07497dc4-a703-46ed-a7c6-28200f4418df.png)

**Comment by Zjm1900** [comment]
麻烦大佬了~

**Comment by Zjm1900** [comment]
谢谢您~

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
