### ISSUE TITLE
联系人和手机号问题

### ISSUE THREAD

**Issue by Gavindzz** [MakiNaruto/Automatic_ticket_purchase#3]
每次自动进入购买界面的时候会显示“输入的联系人含特殊字符或长度不符，请修改后重新提交”以及“您输入的手机号码不符合规范，请重新输入”？我检查了一下，填写的是对的，只有手动刷新后重新填写才能手动继续

**Comment by hewenyu** [comment]
我也试了一下，应该是浏览器加载的问题，你每次send_keys之后加一个time.sleep(1)应该就行了

**Comment by hewenyu** [comment]
> 每次自动进入购买界面的时候会显示“输入的联系人含特殊字符或长度不符，请修改后重新提交”以及“您输入的手机号码不符合规范，请重新输入”？我检查了一下，填写的是对的，只有手动刷新后重新填写才能手动继续

我也试了一下，应该是浏览器加载的问题，你每次send_keys之后加一个time.sleep(1)应该就行了

**Comment by MakiNaruto** [comment]
> 每次自动进入购买界面的时候会显示“输入的联系人含特殊字符或长度不符，请修改后重新提交”以及“您输入的手机号码不符合规范，请重新输入”？我检查了一下，填写的是对的，只有手动刷新后重新填写才能手动继续

我也试了下，确实出现了这个问题，@hewenyu  的办法可行。速度太快确实影响文本的检查，每次输入文本time.sleep(0.5),暂时是可行的。
如果是浏览器加载问题 应该引入 WebDriverWait  ，等待加载完成再进行操作。改天在琢磨琢磨 0.0。

**Comment by tosu** [comment]
同样的问题也会出现在多选购票人的时候出现，会等待页面出现一个特定的元素之后才能勾选第二个购票人
