### ISSUE TITLE
可以运行，但没有反馈

### ISSUE THREAD

**Issue by nanashi-hub** [MakiNaruto/Automatic_ticket_purchase#30]
![image](https://user-images.githubusercontent.com/114349954/195978558-b83e127f-c62c-4f0f-93e8-cc19fc5bd3dc.png)

**Comment by zhangchengyi46** [comment]
+1

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
