### ISSUE TITLE
 大麦现在很多演出都不支持在www.daimai.cn上面买，这个脚本支持移动端大麦m.daimai.cn吗？

### ISSUE THREAD

**Issue by jj023721** [MakiNaruto/Automatic_ticket_purchase#31]
大麦现在很多演出都不支持在www.daimai.cn上面买，这个脚本支持移动端大麦m.daimai.cn吗？

**Comment by xiaohuangwritebug** [comment]
+1

**Comment by zjchen77** [comment]
> 

这是个网页端脚本，当然不支持

**Comment by yuixzero** [comment]
手机端的散了吧

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮

**Comment by jj023721** [comment]
你好，这里是蒋永梁，你的邮件已收到！

**Comment by 18303060635** [comment]
2814249606跑路狗 别上当

**Comment by dishiyicijinqiu** [comment]
![image](https://github.com/MakiNaruto/Automatic_ticket_purchase/assets/9463907/038748a4-ff2c-44b3-9d88-6b5e7881fa74)
你觉得m.daimai.cn就可以了吗？
