### ISSUE TITLE
运行结束没有报错，实际没有订单生成

### ISSUE THREAD

**Issue by zhu0823** [MakiNaruto/Automatic_ticket_purchase#32]
step3_submit_order方法最后buy_status返回如下数据：
`{'ret': ['FAIL_SYS_USER_VALIDATE', 'RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试'], 'data': {'url': 'https://buy.damai.cn:443//multi/trans/createOrder/_____tmd_____/punish?x5secdata=xb6568394a27256ea09b2af72d5497d1ae1677477069a-717315356a1926515014abaac2di53586375a__bx__buy.damai.cn%3A443%2Fmulti%2Ftrans%2Fcreaep=2'}}
`

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
