### ISSUE TITLE
m.damai.cn适配

### ISSUE THREAD

**Issue by BXJC** [MakiNaruto/Automatic_ticket_purchase#35]
1. 求大佬的API来源
2. 大佬有关注过m.damai.cn的API接口嘛，有意开发一个适配m.damai.cn的脚本

**Comment by 17344config** [comment]
你指的是哪些接口？我也想做一个脚本，可以讨论一下

**Comment by KaranaLJX** [comment]
+1，可以加一下联系方式。发现现在都是m.damai.cn的选座购票

**Comment by BXJC** [comment]
已经完成了一份基于自动化方案的适配m.damai.cn的脚本，有需要可以讨论一下，邮件zyzhang0109@gmail.com

**Comment by alanwhy** [comment]
> 已经完成了一份基于自动化方案的适配m.damai.cn的脚本，有需要可以讨论一下，邮件[zyzhang0109@gmail.com](mailto:zyzhang0109@gmail.com)

同学，一起搞啊
