### ISSUE TITLE
代码里没有选择场次的信息

### ISSUE THREAD

**Issue by YFuLin** [MakiNaruto/Automatic_ticket_purchase#38]

**Comment by bwn061693** [comment]
对！  这个我也想问，没有参数指定场次，参考别的项目里面有两个参数，一个是指定场次，一个是指定价格，int的形式定义

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
