### ISSUE TITLE
bx-umidtoken和bx-ua是怎么得到的

### ISSUE THREAD

**Issue by Youthux** [MakiNaruto/Automatic_ticket_purchase#42]
如题，bx-umidtoken貌似是固定不变的，但是bx-ua不知道是怎么算出来的，求大佬帮看

**Comment by define9** [comment]
嗯嗯, bx-umidtoken也可以通过接口拿到, 好像是不变的;
bx-ua好像是淘宝的一套加密, 网上也可以搜到(听说是可以判断是不是selenium和一些非正常的浏览器), 通过addNCParamToRequest加的一个参数,😰那个方法里面好像用到了window,直接运行拿不到这个, 但是浏览器直接运行可以
![image](https://github.com/MakiNaruto/Automatic_ticket_purchase/assets/56190990/194249e4-0806-4a11-a044-4b0104116bf6)

**Comment by laijiexing** [comment]
请问解决了吗

**Comment by guominfang** [comment]
扣了一些代码，能生成 bx-umidtoken和bx-ua，
但是只能处于浏览器状态下，无法在nodejs 或者python环境下去获取，

**Comment by define9** [comment]
> 扣了一些代码，能生成 bx-umidtoken和bx-ua，
> 但是只能处于浏览器状态下，无法在nodejs 或者python环境下去获取，

他应该是检验了一些浏览器自带的变量例如window,document等，应该是需要把它也模拟出来。

**Comment by Youthux** [comment]
> > 扣了一些代码，能生成 bx-umidtoken和bx-ua，
> > 但是只能处于浏览器状态下，无法在nodejs 或者python环境下去获取，
> 
> 他应该是检验了一些浏览器自带的变量例如window,document等，应该是需要把它也模拟出来。

补环境感觉好复杂啊

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮

**Comment by dishiyicijinqiu** [comment]
我已经完美获得了这俩参数了，所有流程都跑通了。然后发现该渠道不支持勾买，mmd

**Comment by dishiyicijinqiu** [comment]
![image](https://github.com/MakiNaruto/Automatic_ticket_purchase/assets/9463907/0e6b73f6-1764-4ba3-963b-5765bfcc8e6c)
然后找到里面的源码，改一下，将那个i，改成window.myi=i,fireyejs.js这个文件。
![image](https://github.com/MakiNaruto/Automatic_ticket_purchase/assets/9463907/43068275-63cc-4e30-ba00-666ffdcbafb2)
然而现在也没用了，都不支持网页端购票了

**Comment by Youthux** [comment]
> ![image](https://user-images.githubusercontent.com/9463907/261959391-0e6b73f6-1764-4ba3-963b-5765bfcc8e6c.png) 然后找到里面的源码，改一下，将那个i，改成window.myi=i,fireyejs.js这个文件。 ![image](https://user-images.githubusercontent.com/9463907/261959697-43068275-63cc-4e30-ba00-666ffdcbafb2.png) 然而现在也没用了，都不支持网页端购票了

你是纯js做的吗

**Comment by jczzq** [comment]
> ![image](https://user-images.githubusercontent.com/9463907/261959391-0e6b73f6-1764-4ba3-963b-5765bfcc8e6c.png) 然后找到里面的源码，改一下，将那个i，改成window.myi=i,fireyejs.js这个文件。 ![image](https://user-images.githubusercontent.com/9463907/261959697-43068275-63cc-4e30-ba00-666ffdcbafb2.png) 然而现在也没用了，都不支持网页端购票了

哈哈哈，真的被dm玩死

**Comment by jczzq** [comment]
> 我已经完美获得了这俩参数了，所有流程都跑通了。然后发现该渠道不支持勾买，mmd

你现在还可以用生成的参数通过登录么？
