### ISSUE TITLE
有抢到5月天的票吗？该渠道不支持购买怎么解决

### ISSUE THREAD

**Issue by CainChao** [MakiNaruto/Automatic_ticket_purchase#43]

**Comment by J-rong** [comment]
网页端不能买票，只能用移动端

**Comment by 250king** [comment]
#37

**Comment by J-rong** [comment]
没，用手机买





------------------ 原始邮件 ------------------
发件人: 耀 ***@***.***&gt;
发送时间: 2023年5月14日 22:36
收件人: MakiNaruto/Automatic_ticket_purchase ***@***.***&gt;
抄送: J-rong ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [MakiNaruto/Automatic_ticket_purchase] 有抢到5月天的票吗？该渠道不支持购买怎么解决 (Issue #43)

**Comment by musicer** [comment]
把 ua改了有人试过吗

**Comment by J-rong** [comment]
Pc端都不行的，你得用手机买





------------------ 原始邮件 ------------------
发件人: musicer ***@***.***&gt;
发送时间: 2023年5月18日 15:04
收件人: MakiNaruto/Automatic_ticket_purchase ***@***.***&gt;
抄送: J-rong ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [MakiNaruto/Automatic_ticket_purchase] 有抢到5月天的票吗？该渠道不支持购买怎么解决 (Issue #43)





 
把 ua改了有人试过吗

**Comment by musicer** [comment]
你好，你的文件我已经收到，我会尽快查看，辛苦了。

**Comment by superjiangs** [comment]
有人抢到五月天的票了吗？

**Comment by rocketsbigfan** [comment]
不能抢了吗

**Comment by deepoceaduck** [comment]
有什么针对app的脚本吗

**Comment by 250king** [comment]
https://github.com/ClassmateLin/dm-ticket
试试这个

**Comment by enchantedlyc** [comment]
> https://github.com/ClassmateLin/dm-ticket 试试这个

这个不能用了 他把aliToken-server的镜像删了 启动不起来了

**Comment by FFAQ** [comment]
> > https://github.com/ClassmateLin/dm-ticket 试试这个
> 
> 这个不能用了 他把aliToken-server的镜像删了 启动不起来了

有什么解决办法不，弄了半天也是到这一步😭

**Comment by FFAQ** [comment]
> https://github.com/ClassmateLin/dm-ticket
> 试试这个

这个还能用吗，镜像安装一直不成功

**Comment by zcf0930** [comment]
> https://github.com/ClassmateLin/dm-ticket 试试这个

镜像被删了，有人有解决方案吗？

**Comment by 250king** [comment]
原作者停止维护了（
不过说实话他这个脚本还是有些缺陷的，有时候可以，有时候会被风控

**Comment by liubang0909** [comment]
有好方案的麻烦踢我下

**Comment by xiechengsiii** [comment]
mark

**Comment by Quentin-Wu** [comment]
mark 求解

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github
