### ISSUE TITLE
运行完打开chrome然后就没了，接着怎么弄

### ISSUE THREAD

**Issue by wushal-117** [MakiNaruto/Automatic_ticket_purchase#45]
![image](https://github.com/MakiNaruto/Automatic_ticket_purchase/assets/80935696/a487d058-ddce-4582-9a40-5d27e3221718)

**Comment by Michaelzhou66** [comment]
没获取到url网址，就是这样的界面

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github

**Comment by zihfvhd** [comment]
> 没有获取到url网址，就是这样的界面

那要怎么解决呀
