### ISSUE TITLE
---------- 获取购买必备参数异常，请重新解析response返回的参数 ---------- window.__INIT_DATA__ = "";     window.ERROR_OBJECT = {       errorCode: '600002',       errorMsg: '{"errorTip":"亲，当前渠道不支持购买此商品，请使用大麦APP下单","errorCode":"B-00203-200-382"}'     }; {'damai': '1', 'channel': 'damai_app', 'umpChannel': '10002', 'atomSplit': '1', 'serviceVersion': '1.8.5'} 订单数据 ---------- 获取购票所需信息失败 ----------

### ISSUE THREAD

**Issue by vanora1111** [MakiNaruto/Automatic_ticket_purchase#46]
up主 这个脚本现在是不是用不了啦，网页dom结构变更了，现在多了一个扫码，以及下面的立即购买

**Comment by ClassmateLin** [comment]
> up主 这个脚本现在是不是用不了啦，网页dom结构变更了，现在多了一个扫码，以及下面的立即购买

可以试试 https://github.com/ClassmateLin/dm-ticket

**Comment by vanora1111** [comment]
忙到现在才打开链接看，那我还得安装一下docker


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MakiNaruto/Automatic_ticket_purchase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 中午12:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MakiNaruto/Automatic_ticket_purchase] ---------- 获取购买必备参数异常，请重新解析response返回的参数 ---------- window.__INIT_DATA__ = "";     window.ERROR_OBJECT = {       errorCode: '600002',       errorMsg: '{"errorTip":"亲，当前渠道不支持购买此商品，请使用大麦APP下单","errorCode":"B-00203-200-382"}'     }; {'damai': '1', 'channel': 'damai_app', 'umpChannel': '10002', 'atomSplit': '1', 'serviceVersion': '1.8.5'} 订单数据 ---------- 获取购票所需信息失败 ---------- (Issue #46)





  
up主 这个脚本现在是不是用不了啦，网页dom结构变更了，现在多了一个扫码，以及下面的立即购买
  
可以试试 https://github.com/ClassmateLin/dm-ticket

**Comment by Areay7** [comment]
解决了吗？

**Comment by bwn061693** [comment]
> > up主 这个脚本现在是不是用不了啦，网页dom结构变更了，现在多了一个扫码，以及下面的立即购买
> 
> 可以试试 https://github.com/ClassmateLin/dm-ticket

大佬你这个我试了，docker仓库没有classmatelin/alitoken-server:v0.1.1这个镜像了  你的项目也没开issue，正愁找不到你呢

**Comment by sanshi2018** [comment]
> > > up主 这个脚本现在是不是用不了啦，网页dom结构变更了，现在多了一个扫码，以及下面的立即购买
> > 
> > 
> > 可以试试 https://github.com/ClassmateLin/dm-ticket
> 
> 大佬你这个我试了，docker仓库没有classmatelin/alitoken-server:v0.1.1这个镜像了 你的项目也没开issue，正愁找不到你呢 @ClassmateLin

@bwn061693 dockerHub上搜一下同名的，改下compose的镜像地址就行了

**Comment by bwn061693** [comment]
> > > > up主 这个脚本现在是不是用不了啦，网页dom结构变更了，现在多了一个扫码，以及下面的立即购买
> > > 
> > > 
> > > 可以试试 https://github.com/ClassmateLin/dm-ticket
> > 
> > 
> > 大佬你这个我试了，docker仓库没有classmatelin/alitoken-server:v0.1.1这个镜像了 你的项目也没开issue，正愁找不到你呢 @ClassmateLin
> 
> @bwn061693 dockerHub上搜一下同名的，改下compose的镜像地址就行了

@sanshi2018 大麦现在H5端都改了  提交订单之后的请求和页面跳转逻辑都不一样了   还能用吗？

**Comment by sanshi2018** [comment]
> 



> > > > > up主 这个脚本现在是不是用不了啦，网页dom结构变更了，现在多了一个扫码，以及下面的立即购买
> > > > 
> > > > 
> > > > 可以试试 https://github.com/ClassmateLin/dm-ticket
> > > 
> > > 
> > > 大佬你这个我试了，docker仓库没有classmatelin/alitoken-server:v0.1.1这个镜像了 你的项目也没开issue，正愁找不到你呢 @ClassmateLin
> > 
> > 
> > @bwn061693 dockerHub上搜一下同名的，改下compose的镜像地址就行了
> 
> @sanshi2018 大麦现在H5端都改了 提交订单之后的请求和页面跳转逻辑都不一样了 还能用吗？ 另外那个项目里面的 使用docker的方式 docker-compose up -d命令也没指定配置文件啊no configuration file provided: not found，即使指定了文件，在执行docker exec -it dm-ticket dm-ticket的时候，也会提示没有dm-ticket这个容器，因为配置文件中根本就没有这个，当然也没有对应的容器启动 dm-ticket]# docker exec -it dm-ticket dm-ticket Error: No such container: dm-ticket
> 
> 让人很费解哈哈哈

@bwn061693 不好用，不懂rust看不懂哪里出错了。将docker-compose.release.yml文件里的镜像地址改为dockerhub找到的镜像

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github
