### ISSUE TITLE
关于signcode.js的提问

### ISSUE THREAD

**Issue by AAAAAkki** [MakiNaruto/Automatic_ticket_purchase#49]
你好，想了解一下这个签名的生成的依据是什么呢，为什么可以通过网站的验证

**Comment by xiaoye-2018** [comment]
这个貌似就是大麦网提供的，官方还有个bx-ua参数没看到，这个代码我还估计运行不了

**Comment by AAAAAkki** [comment]
确实。这个代码的url疑似过时了，大麦网基本全改了一遍。现在我改了一点，sign是对的，但是没有bx-ua＆bx-umid好像给的response不对，js源码做了控制流平坦化的混淆，我没有什么好办法处理。还没有试过用固定参数去爆但是感觉不行。。。

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github
