### ISSUE TITLE
多个购票人 求助

### ISSUE THREAD

**Issue by YimiaoSun** [MakiNaruto/Automatic_ticket_purchase#5]
有多个购票人的时候会显示“购票人信息选中失败，自行查看元素位置”问题  但是选中第二个观影人的解析应该是没错的啊   求助

**Comment by MakiNaruto** [comment]
> 有多个购票人的时候会显示“购票人信息选中失败，自行查看元素位置”问题 但是选中第二个观影人的解析应该是没错的啊 求助


你看看是不是系统只需要一名购票人呀，只需要一名时，无法再加购票人的。

**Comment by gaoyh18** [comment]
可能是因为不能连续点击，你在两个.click命令之间加一个time.sleep(0.5)就好啦，像填写姓名电话那个步骤是一样的道理。我试过的是chrome里面0.5才可以，再小不行，不同浏览器或者场景可以调整试试。

**Comment by YimiaoSun** [comment]
@gaoyh18 加上time.sleep()之后完美解决  感谢！
