### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zhengleee** [MakiNaruto/Automatic_ticket_purchase#53]
TypeError: __init__() got multiple values for argument 'options'

**Comment by wwlwwl2000** [comment]
UCFP:e9c983c6-11b1-4538-fc16-6dca1bb47af2-1692420892561:https://m.uc.cn

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
