### ISSUE TITLE
抢不了

### ISSUE THREAD

**Issue by SongChao160609** [MakiNaruto/Automatic_ticket_purchase#54]
---------- 获取购买必备参数异常，请重新解析response返回的参数 ----------
window.__INIT_DATA__ = "";
    window.ERROR_OBJECT = {
      errorCode: '600002',
      errorMsg: '{"errorTip":"亲，当前渠道不支持购买此商品，请使用大麦APP下单","errorCode":"B-00203-200-382"}'
    };
---------- 获取购票所需信息失败 ----------

**Comment by xiaoyao123456789** [comment]
同问，有解决吗

**Comment by SongChao160609** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github

**Comment by SongChao160609** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by chris911024** [comment]
雲端硬碟：
https://drive.google.com/file/d/1oSt5zWu7JVrW-4M9k4TaSZ2RFA2jcNT7/view?usp=share_link
github：
https://github.com/chris911024/Automated-click-script-plug-in

不爬赤的話可以用看看這個腳本，歡迎大神們pr改進

**Comment by SongChao160609** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SongChao160609** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
