### ISSUE TITLE
生成订单的接口已经变了

### ISSUE THREAD

**Issue by JunKuangKuang** [MakiNaruto/Automatic_ticket_purchase#56]
orderConfirm接口是作用是选座购买，点击确认选座，今天下午我试了一下，发现这个接口已经变成了新接口
https://mtop.damai.cn/h5/mtop.trade.order.build.h5/4.0/ 到这里就没继续了。

拜托大大更新一下吧

**Comment by 123baikai** [comment]
能不能用

**Comment by bwn061693** [comment]
别忙活了    H5渠道能买的 根本就不用抢   H5不能买的才是那些真正你想抢的   但是脚本不能用哈哈哈哈

**Comment by wqhwb** [comment]
> 

啥是H5渠道

**Comment by baijinge0310** [comment]
> > 
> 
> 啥是H5渠道

就是网页上这种，html5

**Comment by diveknown** [comment]
> 

有没有大哥逆向下

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by chris911024** [comment]
雲端硬碟：
https://drive.google.com/file/d/1oSt5zWu7JVrW-4M9k4TaSZ2RFA2jcNT7/view?usp=share_link
github：
https://github.com/chris911024/Automated-click-script-plug-in

不排斥的話可以用看看這個腳本，歡迎大神們pr改進
