### ISSUE TITLE
找不到perform

### ISSUE THREAD

**Issue by davien** [MakiNaruto/Automatic_ticket_purchase#6]
Message: no such element: Unable to locate element: {"method":"css selector","selector":".perform"}
  (Session info: chrome=75.0.3770.100)
一直报这个错，请问怎么解决，百度无果

**Comment by qinyang1018** [comment]
遇见了相同的问题

**Comment by kiaia** [comment]
其实可以crtl+f 找到有perform那行代码 在前面加一个#  把这行注释掉   亲测没有影响  因为这个变量似乎没在其他地方用到-_-

**Comment by MakiNaruto** [comment]
> Message: no such element: Unable to locate element: {"method":"css selector","selector":".perform"}
> (Session info: chrome=75.0.3770.100)
> 一直报这个错，请问怎么解决，百度无果

今天抢票发现这个问题，我换了个抢票目标页就没事了。可能因为目标页定位元素找不到了，该异常没有被捕捉处理，直接结束运行了。
