### ISSUE TITLE
大麦网页现在好像增加一个步骤

### ISSUE THREAD

**Issue by linhangeng** [MakiNaruto/Automatic_ticket_purchase#75]
大佬，你还有在维护吗，现在大麦在进去详情页时，他增加了一步，该怎么弄呢

**Comment by SanctuaryChan** [comment]
现在没用了 大麦不支持网页端买票了

**Comment by 9527fun** [comment]
> 现在没用了 大麦不支持网页端买票了

那现在还有移动端，抢票脚本吗？移动端就和人手差不多了吧。
