### ISSUE TITLE
小程序抢票问题

### ISSUE THREAD

**Issue by rcj60560** [MakiNaruto/Automatic_ticket_purchase#79]
@MakiNaruto @ronething 两位大佬请问可不可以用这个方式
来抢票小程序的票
小程序名称：闪动 - 羽毛球场地

**Comment by MakiNaruto** [comment]
如果没有网页端的话可能得配合抓包进行处理了，抓包后的处理应该和这种方式差不多

> 用这个方式 来抢票小程序的票 小程序名称：闪动 - 羽毛球场地
