### ISSUE TITLE
求周杰伦演唱会门票

### ISSUE THREAD

**Issue by xsw95** [MakiNaruto/Automatic_ticket_purchase#8]
看到大佬16号提交了代码，是专门为抢周杰伦南京站演唱会门票更新的吧，有票吗？

**Comment by MakiNaruto** [comment]
> 看到大佬16号提交了代码，是专门为抢周杰伦南京站演唱会门票更新的吧，有票吗？

并没有抢到 T.T

**Comment by xsw95** [comment]
好吧，，，，，，
